name: "Return value from this"

inputs:
  inputTest:
    description: "App name according to angular.json"
    required: true
outputs:
    outputValue:
      description: "Output value"
      value: ${{ steps.old-output.outputs.result }}

runs:
  using: "composite"
  steps:
    - run: echo InputTest value - ${{ inputs.inputTest }}.
      shell: bash
    - id: output-value-generator
      run: echo "output-value=This is the output value" >> $GITHUB_OUTPUT
      shell: bash
    - id: old-output
      run: echo "::set-output name=result::This is the old way"