name: pull-request
on:
  pull_request:
    types: 
      - opened
      - reopened
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "GITHUB_REF = $GITHUB_REF"
  assign:
    if: ${{ true }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{env.GITHUB_REF}}"
      - run: echo "$GITHUB_REF"
      - uses: delivery-much/actions-assigner@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: dannylith