name: pull-request
on:
  pull_request:
    branches:
      - test
      - main
    types: 
      - opened
      - reopened
    
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "GITHUB_BASE_REF = $GITHUB_BASE_REF"
  assign:
    if: ${{ true }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "${{env.GITHUB_BASE_REF}}"
      - run: echo "$GITHUB_BASE_REF"
      - run: echo "${{env.GITHUB_HEAD_REF}}"
      - run: echo "$GITHUB_HEAD_REF"
      - uses: delivery-much/actions-assigner@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: dannylith