name: Test Get Output Value
on: [workflow_dispatch]

jobs:
  Test-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run testReturningValue ${{ steps.foo.outputs.outputValue }}
        id: foo
        uses: ./.github/actions/test-returning-value
        with:
          inputTest: testing from main action
      - run: echo whatever this ${{ steps.foo.outputs.outputValue }}
        shell: bash